version: '3.9'
services:
    db: 
        image: 'postgres'
        container_name: 'pg_container'
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=test_db
        ports:
            - "54320:5432"
        volumes:
#        - type: bind
#          source: ./pgdata/
#          target: /var/lib/postgresql/data/ 

        - type: bind
          source: ./sql_data/scripts/
          target: /docker-entrypoint-initdb.d/


        - type: bind
          source: ./sql_data/data/
          target: /home/

    bi:
        image: 'metabase/metabase'
        container_name: 'metabase_container'
        ports: 
            - "3000:3000"
        links:
            - db
